In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("hr_analytics.xls")
df

,Age,Gender,Department,MonthlyIncome,TotalWorkingYears,YearsAtCompany,JobSatisfaction,WorkLifeBalance,OverTime,Attrition
0,50,Female,HR,4753,14,8,2,1,Yes,No
1,36,Male,R&D,13123,3,7,3,4,No,No
2,29,Male,HR,19376,16,15,1,3,Yes,No
3,42,Male,HR,9588,19,14,2,4,No,Yes
4,40,Male,R&D,9304,18,8,2,3,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,34,Female,Sales,7986,2,5,4,3,Yes,Yes
996,51,Female,Sales,4481,26,12,4,2,Yes,No
997,44,Male,HR,6731,27,6,4,1,No,No
998,40,Female,Sales,19835,27,9,1,2,No,No
999,53,Female,HR,13758,15,1,2,4,No,No

1. How many rows and columns in the dataset?

In [29]:
df.shape

(1000, 10)

2. What are the data types of each column?

In [30]:
df.dtypes

Age                   int64
Gender               object
Department           object
MonthlyIncome         int64
TotalWorkingYears     int64
YearsAtCompany        int64
JobSatisfaction       int64
WorkLifeBalance       int64
OverTime             object
Attrition            object
dtype: object

3. Any missing values?

In [31]:
df.isna()

,Age,Gender,Department,MonthlyIncome,TotalWorkingYears,YearsAtCompany,JobSatisfaction,WorkLifeBalance,OverTime,Attrition
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

In [37]:
df.isna().sum()

Age                  0
Gender               0
Department           0
MonthlyIncome        0
TotalWorkingYears    0
YearsAtCompany       0
JobSatisfaction      0
WorkLifeBalance      0
OverTime             0
Attrition            0
dtype: int64

4. Any duplicate values?

In [32]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [38]:
df.duplicated().sum()

np.int64(0)

5. Number of Employees

In [33]:
len(df)

1000

6. Number of Departments

In [34]:
df["Department"].nunique()

3

7. Display all Departments

In [36]:
df["Department"].unique()

array(['HR', 'R&D', 'Sales'], dtype=object)

8. Average Employee Age

In [23]:
sum(df["Age"]) / len(df["Age"])

40.947

9. Minimum and Maximum Employees

In [12]:
df["Age"].min()

22

In [13]:
df["Age"].max()

59

10. Gender Distribution of Employees

In [14]:
df["Gender"].value_counts()

Gender
Male      504
Female    496
Name: count, dtype: int64

11. Number of Employees in each department

In [15]:
df["Department"].value_counts()

Department
HR       352
Sales    343
R&D      305
Name: count, dtype: int64

12. How many employees have more than 10 years of experience - total working years?

In [24]:
len(df[df["TotalWorkingYears"] > 10])

720

13. How many employees have been with the company for more than 5 years?

In [25]:
len(df[df["YearsAtCompany"] > 5])

752

14. Average monthly income in each department

In [18]:
df.groupby("Department")["MonthlyIncome"].mean()

Department
HR       11604.042614
R&D      11461.272131
Sales    11417.247813
Name: MonthlyIncome, dtype: float64

15. How many employees have left the company in each department?

In [26]:
df[df["Attrition"] == "Yes"]["Department"].value_counts()

Department
R&D      74
HR       70
Sales    59
Name: count, dtype: int64